POST {{hostaddress}}/ForumThread
Content-Type: application/json

{
  "Title" : "My first proper fitness thread",
  "Content" : "This is the body of the thread"
}
###
GET {{hostaddress}}/ForumThread/My first proper fitness thread
###
GET {{hostaddress}}/ForumThread/xyz
###
POST {{hostaddress}}/ForumThread
Content-Type: application/json

{
  "Title" : ""
}
